### ISSUE TITLE
Support up-to-date dependencies

### ISSUE THREAD

**Issue by Jouby** [jctophefabre/i18n_omatic#14]
In [pub Points score page](https://pub.dev/packages/i18n_omatic/score) : `0/10 points: All of the package dependencies are supported in the latest version`

Needs to update following packages : 

- `args` to `2.0.0`
- `glob` to `2.0.0`
- `yaml` to `3.0.0`

**Comment by jctophefabre** [comment]
Thanks @Jouby for this issue.
I've noticed these needed updates related to the latest release. I will update theses dependencies once I have checked that they won't introduce any regression.

**Comment by jctophefabre** [comment]
I have checked the versions in the dependency chain. It appears that the minimum required version for Flutter is 1.26, but this version is still in beta channel.
So, I will perform this update once Flutter 1.26 will be available in the stable channel.
